### ISSUE TITLE
build.sh ships custom kernels built for the dev interpreter, not the bundle's cpython-3.11 (silently non-loading)

### ISSUE THREAD

**Issue by dlond** [dlond/omlx#2]
## Summary

`apps/omlx-mac/Scripts/build.sh release --with-custom-kernel` compiles the native custom kernels with the **developer's** interpreter, but the staged `.app` runs the **venvstacks cpython-3.11** layer. When those two differ — which is the default on a current macOS, not an edge case — the extension modules get an ABI tag the bundled interpreter will never look for. Every kernel silently fails to load and the app falls back to the slow paths.

The build exits 0 and reports success.

## Evidence

Staged bundle from a clean `build.sh release --with-custom-kernel`:

```console
$ ls oMLX.app/Contents/Resources/omlx/custom_kernels/*/_ext*.so | sed 's|.*/||' | sort -u
_ext.cpython-313-darwin.so

$ oMLX.app/Contents/Resources/Python/cpython-3.11/bin/python3 -V
Python 3.11.10
```

CPython 3.11 searches for `_ext.cpython-311-darwin.so` (or `_ext.abi3.so`), so the shipped file is invisible to it. Checked inside the bundle's own interpreter, with `mlx` importing fine from the same `sys.path` to rule out a bad probe:

```
mlx imports OK: mlx.core
  bonsai          False | No module named 'omlx.custom_kernels.bonsai._ext'
  glm_moe_dsa     False | cannot import name '_ext' from partially initialized module ...
  minimax_m3      False | cannot import name '_ext' from partially initialized module ...
  qwen35_prefill  False | cannot import name '_ext' from partially initialized module ...
```

All four are the "native extension is present but failed to load; falling back to the slow path" case — i.e. the exact ~30x GLM-5.2 prefill regression `README.md` warns about, in a bundle that was built specifically to avoid it.

## Root cause

`apps/omlx-mac/Scripts/build.sh:373`:

```bash
"$PYTHON_BIN" setup.py build_ext --inplace --force --with-custom-kernel
```

`PYTHON_BIN` defaults to a plain `PATH` lookup (`build.sh:192`):

```bash
PYTHON_BIN="${PYTHON_BIN:-$(command -v python3 || true)}"
```

The bundle's runtime, meanwhile, is pinned in `packaging/venvstacks.toml:15`:

```toml
python_implementation = "cpython@3.11.10"
```

Nothing reconciles the two. The `.so` is built for whatever `python3` happens to be, then rsync'd verbatim into a 3.11 bundle.

## Why the guards miss it

The post-build checks (`build.sh:375-380`) only assert that the **metallibs** exist:

```bash
[ -f ".../omlx_glm_kernels.metallib" ] || die "custom kernel build finished but GLM metallib is missing."
```

Metallibs are Python-version-agnostic, so they are present and correct regardless. Nothing inspects the `.so` ABI tag.

Note that `_check_custom_kernel_nanobind` already guards a *narrower* ABI hazard — the nanobind pin from #2139 — against the same `PYTHON_BIN`. It verifies that the interpreter building the extension has the right nanobind, but not that it is the interpreter the extension will be loaded by.

## Reproducibility

This is the default path, not an unusual setup:

- `pyproject.toml` declares `requires-python = ">=3.11,<3.14"`, so a fresh `uv sync` resolves to **3.13**.
- The `README.md` "Development" flow (`pip install -e ".[dev]"`) uses whatever `python3` is on `PATH`; on macOS 26 that is **3.13.12**.

Either documented route produces a broken bundle. It only works if the developer's interpreter happens to be 3.11.

## Suggested fix

1. Build the kernels with the interpreter that will load them, rather than `PYTHON_BIN` — the runtime layer is already staged at `Contents/Resources/Python/cpython-3.11/bin/python3` (note venvstacks strips `pip` from it, so a seeded 3.11 environment may be needed to run `setup.py`).
2. Add an ABI assertion beside the existing metallib guards, so this can never pass silently again:

```bash
expected_tag="cpython-$(echo "$runtime_version" | tr -d .)-darwin"
for so in "$REPO_ROOT"/omlx/custom_kernels/*/_ext*.so; do
    case "$so" in
        *"$expected_tag"*) ;;
        *) die "custom kernel $so does not match the bundle runtime ABI ($expected_tag)" ;;
    esac
done
```

3. Optionally have `native_kernel_status()` surface an explicit ABI-mismatch reason, since "No module named ..._ext" is a misleading symptom for a file that is sitting right there on disk.

## Environment

- macOS 26.5.2, Apple Silicon, Xcode 26.6 + MetalToolchain component
- venvstacks 0.7.0, bundle runtime cpython-3.11.10
- Dev interpreter 3.13.12; kernels themselves build and load correctly under 3.13 outside the bundle

**Comment by dlond** [comment]
Note for anyone triaging this: **aligning the developer's interpreter to 3.11 makes the symptom vanish, but it is a workaround, not the fix.**

Recreating the dev venv at 3.11 and rebuilding produces a correct bundle:

```
$ find oMLX.app/Contents/Resources/omlx/custom_kernels -name '*.so' | sed 's|.*/||' | sort -u
_ext.cpython-311-darwin.so

# inside the bundle's own interpreter
bonsai          True
glm_moe_dsa     True
minimax_m3      True
qwen35_prefill  True
```

That is the first time all four have loaded inside the bundle. But it works only because `PYTHON_BIN` now *happens* to match `venvstacks.toml`'s `cpython@3.11.10`. Nothing enforces the relationship, so the bug is intact for anyone on 3.12 or 3.13 — which is what a default `uv sync` or a `pip install -e ".[dev]"` against a current system `python3` gives you. Please don't close this on the basis of a clean build on an aligned machine; that is precisely how it survived this long.

Two adjacent things noticed while verifying:

1. **`CUSTOM_KERNEL_DIRS` is missing `bonsai`.** `setup.py` builds four extensions (`bonsai`, `glm_moe_dsa`, `minimax_m3`, `qwen35_prefill`), but `build.sh:112` lists only the last three. That array drives both `_clean_custom_kernel_build_artifacts` (`build.sh:232`) and the deployment-target check (`build.sh:276`), so bonsai's `.so` is neither cleaned nor validated. In practice a stale `_ext.cpython-313-darwin.so` from an earlier build survived the rebuild and was copied into the bundle next to the correct `cpython-311` one — so the bundle shipped both ABIs. Adding bonsai to the array fixes the accumulation and extends the min-macOS check to it.

2. **`nanobind` is not reachable after a clean `uv sync`.** It is declared in `[build-system].requires`, which serves isolated builds, but `build.sh` runs `setup.py build_ext` *without* isolation and so needs it importable from `PYTHON_BIN`. Every venv recreate therefore requires a manual `uv pip install nanobind==2.13.0` before `build.sh --with-custom-kernel` will run. Adding it to the `dev` dependency group (kept in step with the existing pin) would make `uv sync --dev` sufficient.

**Comment by dlond** [comment]
**Correction to the "Reproducibility" section above.**

I wrote that macOS 26's system `python3` is 3.13.12 and that `pip install -e ".[dev]"` against it reproduces this. That measurement was wrong: `/usr/bin/python3` is a shim that honours an active `VIRTUAL_ENV`, and I read it with one exported. In a clean environment it is:

```console
$ env -i /usr/bin/python3 -V
Python 3.9.6        # /Applications/Xcode.app/Contents/Developer/usr/bin/python3
```

That is below `requires-python = ">=3.11"`, so the system interpreter cannot install the project at all — it is not a route into this bug.

The uv route is the real default path, and it does hold. With no `.python-version` present, uv honours `requires-python` and selects the newest permitted:

```console
$ uv python find          # no pin
.../uv/python/cpython-3.13-macos-aarch64-none/bin/python3.13

$ uv python find          # with .python-version = 3.11
.../uv/python/cpython-3.11-macos-aarch64-none/bin/python3.11
```

So a plain `uv sync` lands on 3.13 against a 3.11 bundle runtime, which is how this was hit. The severity and the fix are unchanged; only the second reproduction route was wrong.
